boards/urls.py
from django.urls import path

from . import views

app_name = 'boards'
urlpatterns = [
    path('', views.PostingListView.as_view(), name='postings'),
    path('<int:posting_id>', views.PostingDetailView.as_view(), name='posting_detail'),
    path('', views.PostingCreateView.as_view(), name='posting_create'),
    path('write', views.PostingCreateWriteView.as_view(), name='posting_create_view'),
    path('<int:posting_id>', views.PostingDeleteView.as_view(), name='posting_delete'),
]

pracBoard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('boards.urls')),
]

boards/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from users.models import Writer


class Posting(models.Model):
    writer = models.ForeignKey(Writer, on_delete=models.SET_NULL, related_name='postings', null=True)
    title = models.CharField(_('제목'), max_length=50)
    content = models.TextField(_('내용'))

    created_datetime = models.DateTimeField(auto_now_add=True, blank=True)
    updated_datetime = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        ordering = ('-created_datetime', )

    def __str__(self):
        return self.title

users/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

User = get_user_model()


class Writer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user', blank=True, null=True)

    name = models.CharField(_('이름'), max_length=20)

    created_datetime = models.DateTimeField(auto_now_add=True, blank=True)
    updated_datetime = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return self.name

boards/forms.py
from django import forms

from .models import Posting


class PostingForm(forms.ModelForm):

    class Meta:
        model = Posting
        fields = ('writer', 'title', 'content', )

    # push 전에 삭제하기
    def clean(self):
        cleaned_data = super(PostingForm, self).clean()
        if self.errors:
            return cleaned_data
        return cleaned_data

boards/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import FormView, DeleteView
from django.views import View
from django.http import JsonResponse

from .models import Posting
from .forms import PostingForm


class PostingListView(ListView):
    """
    게시물 리스트 불러오기
    """
    model = Posting
    template_name = 'boards/boards.html'
    http_method_names = ['get']
    context_object_name = 'postings'

    def get_queryset(self):
        return Posting.objects.select_related(
            'writer',
        ).all()


class PostingDetailView(DetailView):
    """
    게시물 상세 페이지
    """
    model = Posting
    template_name = 'boards/board_detail.html'
    http_method_names = ['get']
    context_object_name = 'posting'
    pk_url_kwarg = 'posting_id'

    def get_queryset(self):
        return Posting.objects.select_related(
            'writer',
        ).all()


class PostingCreateView(FormView):
    """
    게시물 생성하기
    """
    model = Posting
    http_method_names = ['post']
    form_class = PostingForm

    def form_valid(self, form):
        posting = form.save()
        return JsonResponse({'writer': posting.writer, 'id': posting.id, 'content': posting.content,
                             'created_datetime': posting.created_datetime}, status=200)

    def form_invalid(self, form):
        return JsonResponse({'msg': {**form.errors.get_json_data()}}, status=400)


class PostingDeleteView(DeleteView):
    """
    게시물 삭제하기
    """
    model = Posting
    http_method_names = ['delete']
    pk_url_kwarg = 'posting_id'

    def delete(self, request, *args, **kwargs):
        posting = get_object_or_404(Posting, pk=self.kwargs.get(self.pk_url_kwarg))
        print(11111)
        posting.delete()
        return JsonResponse({'msg': 'success'}, status=200)


class PostingCreateWriteView(View):
    model = Posting
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        return render(request, 'boards/posting_create.html')

users/views.py
from django.shortcuts import render

# Create your views here.

templates/boards/board_detail.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    {% block title %}
    <title>title</title>
    {% endblock %}

    {% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/board.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="{% static 'js/board.js' %}"></script>
    {% endblock %}
</head>
<body>
    <div class="board">
        <h2 class="center">{{ posting.title }}</h2>
        <div >
            <input type="hidden" name="posting-id" value="{{ posting.pk }}">
            <div class="posting-detail">
                <p>작성자 : <input readonly type="text" name="writer" value="{{ posting.writer.name }}"></p>
                <p>작성일 : <input readonly type="text" name="created_datetime" value="{{ posting.created_datetime }}"></p>
            </div>
            
            <div class="posting-content"><textarea>{{ posting.content }}</textarea></div>
            <div class="btn-group">
                <button>수정</button>
                <button>삭제</button>
                <button>확인</button>
            </div>
        </div>
    </div>
</body>

templates/boards/boards.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    {% block title %}
    <title>title</title>
    {% endblock %}

    {% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/board.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="{% static 'js/board.js' %}"></script>
    {% endblock %}
</head>
<body>
    <div class="board">
        <h2 class="center">게시판</h2>
        <button><a href="{% url 'boards:posting_create_view' %}">글쓰기</a></button>
        <table>
            <thead>
                <tr>
                    <th>No</th>
                    <th>제목</th>
                    <th>작성자</th>
                    <th>작성일</th>
                </tr>
            </thead>
            <tbody>
            {% if postings %}
            {% for posting in postings %}
                <tr>
                    <td>{{ posting.pk }}</td>
                    <td><a href="{% url 'boards:posting_detail' posting.pk %}">{{ posting.title }}</a></td>
                    
                    <td>{{ posting.writer.name }}</td>
                    <td>{{ posting.created_datetime }}</td>
                </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td></td>
            </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
</body>
</html>

templates/boards/posting_create.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    {% block title %}
    <title>title</title>
    {% endblock %}

    {% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/board.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="{% static 'js/board.js' %}"></script>
    {% endblock %}
</head>
<body>
    <div class="board">
        <h2 class="center">게시글 작성</h2>
        <div >
            <input type="hidden" name="posting-id" value="{{ posting.pk }}">
            <div class="posting-detail">
                <p>작성자 : <input readonly type="text" name="writer" value="{{ posting.writer.name }}"></p>
                <p>작성일 : <input readonly type="text" name="created_datetime" value="{{ posting.created_datetime }}"></p>
            </div>
            
            <div class="posting-content"><textarea></textarea></div>
            <div class="btn-group">
                <button>취소</button>
                <button>저장</button>
            </div>
        </div>
    </div>
</body>